# webpack build
#  docker-composer run --rm vuejs webpack
version: "3"
services:
  vuejs:
    build:
      ./docker/node
    ports:
      - 8080:8080
    working_dir: /app
    volumes:
      - ./vuejs:/app
    command: npm run dev